// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaB-icFzcUBOdON1qtpDk5pwena1ExgMo',
    appId: '1:952425570414:web:d0998810103cba4bbec67f',
    messagingSenderId: '952425570414',
    projectId: 'yak-biseo',
    authDomain: 'yak-biseo.firebaseapp.com',
    storageBucket: 'yak-biseo.firebasestorage.app',
    measurementId: 'G-ETCHEXHBPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5vAyKJcTa9GaYohT-rP5rOr2ovm96iuU',
    appId: '1:952425570414:android:b50341ebfd8a6477bec67f',
    messagingSenderId: '952425570414',
    projectId: 'yak-biseo',
    storageBucket: 'yak-biseo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQzMcGq1od4aYHkYJvlOkRBA4nL40CmH0',
    appId: '1:952425570414:ios:55732de28929ff9ebec67f',
    messagingSenderId: '952425570414',
    projectId: 'yak-biseo',
    storageBucket: 'yak-biseo.firebasestorage.app',
    iosBundleId: 'com.vibecode.yakbiseo',
  );
}
